[tool.poetry]
name = "group-33"
version = "0.1.0"
description = ""
authors = ["Lukas Mahler <lukas.mahler@student.tuwien.ac.at>"]
readme = "README.md"

packages = [
    { include = "group_33", from = "src"},
    { include = "ebrec", from = "src"}
]

[tool.poetry.dependencies]
python = "^3.11"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
